"""Change Source title uniqueness

Revision ID: 07aa676d4622
Revises: 1b3874f6e916
Create Date: 2026-01-21 12:04:16.177901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07aa676d4622'
down_revision: Union[str, Sequence[str], None] = '1b3874f6e916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_title'), table_name='sources')
    op.create_index(op.f('ix_sources_title'), 'sources', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_title'), table_name='sources')
    op.create_index(op.f('ix_sources_title'), 'sources', ['title'], unique=True)
    # ### end Alembic commands ###
